version: "3.9"

services:
  db:
    image: postgres:16
    container_name: subscription_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:latest
    container_name: subscription_migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    entrypoint: ["sh", "-c"]
    command: >
      "migrate -path=/migrations -database postgres://postgres:postgres@db:5432/subscriptions?sslmode=disable up || true"

  app:
    build: .
    container_name: subscription_app
    depends_on:
      - db
      - migrate
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.yaml:/app/config.yaml
    environment:
      CONFIG_PATH: "/app/config.yaml"

volumes:
  db_data:
